# before_script: "npm install"

services:
   - mongodb
   - redis-server
#   - couchdb

language: node_js
node_js:
  - "0.10"
  - "0.8"

branches:
  only:
    - master

notifications:
  email:
    - adriano@raiano.ch